# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="发布说说的用户ID"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="说说内容"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="说说状态"
                    ),
                ),
                (
                    "is_top",
                    models.IntegerField(
                        blank=True, default=2, null=True, verbose_name="是否置顶"
                    ),
                ),
                (
                    "like_times",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="点赞次数"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "blog_talk",
            },
        ),
        migrations.CreateModel(
            name="TalkPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "talk_id",
                    models.IntegerField(blank=True, null=True, verbose_name="说说的ID"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="图片地址"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "blog_talk_photo",
            },
        ),
    ]
