# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_id",
                    models.IntegerField(blank=True, null=True, verbose_name="评论父级id"),
                ),
                (
                    "for_id",
                    models.IntegerField(blank=True, null=True, verbose_name="评论的对象id"),
                ),
                (
                    "type",
                    models.IntegerField(blank=True, null=True, verbose_name="评论类型"),
                ),
                (
                    "from_id",
                    models.IntegerField(blank=True, null=True, verbose_name="评论人id"),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="评论人昵称"
                    ),
                ),
                (
                    "from_avatar",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="评论人头像"
                    ),
                ),
                (
                    "to_id",
                    models.IntegerField(blank=True, null=True, verbose_name="被回复的人id"),
                ),
                (
                    "to_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="被回复人的昵称"
                    ),
                ),
                (
                    "to_avatar",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="被回复人的头像"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="评论内容"
                    ),
                ),
                ("thumbs_up", models.IntegerField(default=0, verbose_name="评论点赞数")),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ip地址"
                    ),
                ),
            ],
            options={
                "db_table": "blog_comment",
            },
        ),
    ]
