# Generated by Django 5.1.1 on 2024-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="评论内容"),
        ),
    ]
