# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_id",
                    models.IntegerField(blank=True, null=True, verbose_name="相册 ID"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="图片地址"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "blog_photo",
            },
        ),
        migrations.CreateModel(
            name="PhotoAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_name",
                    models.CharField(
                        blank=True, max_length=26, null=True, verbose_name="相册名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=55, null=True, verbose_name="相册描述信息"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "album_cover",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="相册封面"
                    ),
                ),
            ],
            options={
                "db_table": "blog_photo_album",
            },
        ),
    ]
