"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tzfr$$a#*)r-h_gfvw-nulric28@-#95y4w9^j*xz&y-wep@8i"

# set minio environment config
MINIO_PATH = '110.41.38.135'
MINIO_PORT = 9000
MINIO_ACCESSKEY = 'dhVqZarltCSNijTBIO9r'
MINIO_SECRETKEY = 'VKwZwwRxls6IQAdozQNhLxZb1SPZh3uM8tpREviV'
MINIO_BUCKET = 'blog-images'

APP_PORT = 8000
BASEURL = 'http://127.0.0.1:8000/'
ADMIN_PASSWORD = 'admin123456'

# JWT secretkey
JWT_SECRET = 'blog'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "channels",
    "apps.article",
    "apps.category",
    "apps.chat",
    "apps.comment",
    "apps.config",
    "apps.header",
    "apps.like",
    "apps.links",
    "apps.message",
    "apps.notify",
    "apps.photo",
    "apps.recommend",
    "apps.tag",
    "apps.talk",
    "apps.user",
]

# 指定 ASGI 应用程序
ASGI_APPLICATION = 'backend.asgi.application'     # 替换为项目名称

# 选择使用的 Channels 层（例如 Redis）
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # 使用内存通道（可选）
        # 如果使用 Redis，可以使用以下配置：
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [("127.0.0.1", 6379)],  # 替换为您的 Redis 配置
        # },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "middlewares.AuthMiddleware",
    "middlewares.NeedAdminAuthNotNeedSuperMiddleware",
    "middlewares.AdminAuthMiddleware",
    "middlewares.SuperAdminAuthMiddleware",
    "middlewares.RateLimitMiddleware"
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'personal_website',
        'HOST': '110.41.38.135',
        'PORT': 3306,
        'USER': 'personal_website_adminer',
        'PASSWORD': '123456',
        'OPTIONS': {
            'charset': 'utf8mb4',       # 使得可以存储emoji字符
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'statics']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

