# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "文章"), (2, "说说"), (3, "留言"), (4, "评论")],
                        null=True,
                        verbose_name="点赞类型",
                    ),
                ),
                (
                    "for_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="点赞id 文章id 说说id 留言id"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="点赞用户id"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="点赞IP"
                    ),
                ),
            ],
            options={
                "db_table": "blog_like",
            },
        ),
    ]
