# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=55, unique=True, verbose_name="分类名称"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "blog_category",
            },
        ),
    ]
