# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="标签"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="留言内容"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#676767",
                        max_length=255,
                        null=True,
                        verbose_name="字体颜色",
                    ),
                ),
                (
                    "font_size",
                    models.IntegerField(
                        blank=True, default=12, null=True, verbose_name="字体大小"
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="背景颜色"
                    ),
                ),
                (
                    "bg_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="背景图片"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="留言用户的id"),
                ),
                (
                    "like_times",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="点赞次数"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "font_weight",
                    models.IntegerField(
                        blank=True, default=500, null=True, verbose_name="字体宽度"
                    ),
                ),
                (
                    "nick_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="游客用户的昵称"
                    ),
                ),
            ],
            options={
                "db_table": "blog_message",
            },
        ),
    ]
