# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog_name",
                    models.CharField(
                        default="范同学的博客", max_length=55, verbose_name="博客名称"
                    ),
                ),
                (
                    "blog_avatar",
                    models.CharField(
                        default="https://mrzym.gitee.io/blogimg/html/rabbit.png",
                        max_length=255,
                        verbose_name="博客头像",
                    ),
                ),
                (
                    "avatar_bg",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="博客头像背景图"
                    ),
                ),
                (
                    "personal_say",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="个人签名"
                    ),
                ),
                (
                    "blog_notice",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="博客公告"
                    ),
                ),
                (
                    "qq_link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="QQ链接"
                    ),
                ),
                (
                    "we_chat_link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="微信链接"
                    ),
                ),
                (
                    "github_link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="GitHub链接"
                    ),
                ),
                (
                    "git_ee_link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Git EE链接"
                    ),
                ),
                (
                    "bilibili_link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bilibili链接"
                    ),
                ),
                (
                    "view_time",
                    models.BigIntegerField(default=0, verbose_name="博客被访问的次数"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "we_chat_group",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="微信群图片"
                    ),
                ),
                (
                    "qq_group",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="QQ群图片"
                    ),
                ),
                (
                    "we_chat_pay",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="微信收款码"
                    ),
                ),
                (
                    "ali_pay",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="支付宝收款码"
                    ),
                ),
            ],
            options={
                "db_table": "blog_config",
            },
        ),
    ]
