# Generated by Django 5.1.1 on 2024-10-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="blog_avatar",
            field=models.CharField(
                default="https://mrzym.gitee.io/blogimg/html/rabbit.png",
                max_length=255,
                null=True,
                verbose_name="博客头像",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="blog_name",
            field=models.CharField(
                default="范同学的博客", max_length=55, null=True, verbose_name="博客名称"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="view_time",
            field=models.BigIntegerField(default=0, null=True, verbose_name="博客被访问的次数"),
        ),
    ]
