# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="账号名唯一",
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                ("role", models.IntegerField(default=2, verbose_name="用户角色")),
                (
                    "nick_name",
                    models.CharField(default="", max_length=255, verbose_name="用户昵称"),
                ),
                (
                    "avatar",
                    models.CharField(default="", max_length=255, verbose_name="用户头像"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        default="", max_length=255, verbose_name="用户QQ，用于联系"
                    ),
                ),
                (
                    "ip",
                    models.CharField(default="", max_length=255, verbose_name="IP属地"),
                ),
            ],
            options={
                "db_table": "blog_user",
            },
        ),
    ]
