# Generated by Django 5.1.1 on 2024-10-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ip",
            field=models.CharField(
                default="", max_length=255, null=True, verbose_name="IP属地"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="qq",
            field=models.CharField(
                default="", max_length=255, null=True, verbose_name="用户QQ，用于联系"
            ),
        ),
    ]
