# Generated by Django 5.1.1 on 2024-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=555, null=True, verbose_name="通知内容"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, null=True, verbose_name="通知给谁"),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "文章"), (2, "说说"), (3, "留言"), (4, "友链")],
                        null=True,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "to_id",
                    models.IntegerField(blank=True, null=True, verbose_name="目标ID"),
                ),
                (
                    "isView",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="是否被查看"
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "blog_notify",
            },
        ),
    ]
