# Generated by Django 5.1.1 on 2024-10-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_content",
            field=models.TextField(blank=True, null=True, verbose_name="文章内容"),
        ),
    ]
